# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-06 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='location',
            new_name='address',
        ),
    ]
